@startuml UC_19
hide footbox


actor ":Admin" as Admin
boundary ":VerificationRequestView" as PendingRequestsView
control ":VerificationRequest\nController" as VerificationRequestController
entity ":VerificationRequest" as PendingRequests

Admin ++
  Admin -> PendingRequestsView: 1. // choose view pending requests
  PendingRequestsView ++
    PendingRequestsView -> VerificationRequestController: 2. // get pending requests ()
    VerificationRequestController ++
      VerificationRequestController -> PendingRequests: 3. // query requests ()
        PendingRequests ++
        PendingRequests --> VerificationRequestController: query results message
      VerificationRequestController --> PendingRequestsView: 4. // display pending requests ()


  Admin -> PendingRequestsView: 5. // select specific request
    PendingRequestsView -> VerificationRequestController: 6. // get specific request ()
      VerificationRequestController -> PendingRequests: 7. // query specific request ()
        PendingRequests --> VerificationRequestController: query results message
      VerificationRequestController --> PendingRequestsView: 8. // display specific request ()

  Admin -> PendingRequestsView: 9. // update request status
    PendingRequestsView -> VerificationRequestController: 10. // update request ()
      VerificationRequestController -> PendingRequests: 11. // update request ()
        PendingRequests --> VerificationRequestController: update success message
      VerificationRequestController --> PendingRequestsView: update success message
    PendingRequestsView --> Admin: update success message

alt Invalid status
  PendingRequests --> VerificationRequestController: invalid status message
  PendingRequests --
    VerificationRequestController --> PendingRequestsView: invalid status message
    VerificationRequestController --
    PendingRequestsView --> Admin: invalid status message
    PendingRequestsView --
end

@enduml