@startuml 
hide footbox

actor ":User" as User
participant ":PaymentView" as PaymentView
participant ":PaymentController" as PaymentController
participant ":IPaymentDatabase" as Payment
participant  ":BankingSystemBoundary" as BankingSystemBoundary
actor ":Banking System" as BankingSystem

User ++
  User -> PaymentView: 1. initiatePaymentAction()
  PaymentView ++
    PaymentView -> PaymentController: 2.triggerPayment()
    PaymentController ++
      PaymentController -> PaymentView: 3. displayPaymentDetails()
      PaymentView --> User: return payment details screen

  
  User -> PaymentView: 4. makePayment(...)
    PaymentView -> PaymentController: 5. makePayment(...)
      PaymentController ->  BankingSystemBoundary: 6. transmitPaymentRequest(...)
      BankingSystemBoundary ++
        BankingSystemBoundary -> BankingSystem: 7. transmitPaymentRequest(...)
        BankingSystem ++
          BankingSystem -->  BankingSystemBoundary: authentication request message

        BankingSystemBoundary --> PaymentController: authentication request message
      PaymentController --> PaymentView: authentication request message
    PaymentView --> User: authentication request message
  User -> PaymentView: 8. provideAuthenticationDetails(...)
    PaymentView -> PaymentController: 9. provideAuthenticationDetails(...)
      PaymentController ->  BankingSystemBoundary: 10. transferEncryptedDetails(...)
        BankingSystemBoundary -> BankingSystem: 11. transferEncryptedDetails(...)

alt Authentication Success
    BankingSystem -->  BankingSystemBoundary: success authentication message
    
      BankingSystemBoundary --> PaymentController: success authentication message
      
        PaymentController -> PaymentView: 12.1. displayPaymentConfirmation()
        
          PaymentView --> User: ask for confirmation


        User -> PaymentView: 13.1. confirmPurchase()
        
          PaymentView -> PaymentController: 14.1. confirmPurchase()
          
            PaymentController ->  BankingSystemBoundary: 15.1. transactionRequest(...)
            
              BankingSystemBoundary -> BankingSystem: 16.1. transactionRequest(...)
              
                BankingSystem -->  BankingSystemBoundary: transaction response message
                
              BankingSystemBoundary --> PaymentController: transaction response message
              
            PaymentController -> Payment: 17.1. setPaymentDetails(...)
            
            Payment ++
              Payment --> PaymentController: payment details message
              
            Payment --
            PaymentController -> PaymentView: 18.1. displayPaymentDetails()
            PaymentView --> User: return payment details screen
          

    alt Insufficient Funds
      BankingSystem -->  BankingSystemBoundary: insufficient funds message
      
        BankingSystemBoundary --> PaymentController: insufficient funds message
        
          PaymentController --> PaymentView: insufficient funds message
          
            PaymentView --> User: insufficient funds message
            
    end

else Authentication Failure
  BankingSystem -->  BankingSystemBoundary: fail authentication message
      BankingSystem --
      BankingSystemBoundary --> PaymentController: fail authentication message
      BankingSystemBoundary --
        PaymentController --> PaymentView: fail authentication message
        PaymentController --
          PaymentView --> User: fail authentication message
          
        deactivate PaymentView
      deactivate PaymentController
end

@enduml
