@startuml UC_18
hide footbox


actor ":Customer" as Customer
participant ":AuctionView" as AuctionView
participant ":AuctionController" as AuctionController
participant ":IBidDatabase" as Bid
Customer ++
  Customer -> AuctionView : 1. enterBidAmount()
  activate AuctionView
    AuctionView -> AuctionController : 2.validateBid()
    activate AuctionController
      AuctionController -> AuctionController : 3. validateBid()
      AuctionController -> Bid : 4. createBid()
      activate Bid
        Bid --> AuctionController : new highest bid message

      AuctionController --> AuctionView : new highest bid message
    AuctionView --> Customer : new highest bid message

alt Invalid Bid Amount
  AuctionController --> AuctionView : invalid bid message
    AuctionView --> Customer : invalid bid message
end

opt Automatic Bid
    Customer -> AuctionView : 1.1. setMaxBid()
      AuctionView -> AuctionController : 2.1. setMaxBid()
    loop Until Auction Ends
      alt Not Top Bidder & Max Bid Not Exceeded
        AuctionController -> Bid : 3.2 createBid()
          Bid --> AuctionController : new highest bid message
        deactivate Bid
          AuctionController --> AuctionView : new highest bid message
        deactivate AuctionController
          AuctionView --> Customer : new highest bid message
        deactivate AuctionView
      end
    end
end

@enduml