@startuml 
hide footbox

actor ":User" as User
participant ":AuctionListView" as AuctionView
participant ":SearchController" as SearchController
participant ":IAuctionDatabase" as Auction

User ++
opt Manual Search
    User -> AuctionView: 1.1. fillSearchBar(keywords)
    
    activate AuctionView
      AuctionView -> SearchController: 2.1. searchByKeywords(keywords)
      
      activate SearchController
        SearchController -> Auction: 3.1. getAuctionList(query)
          
          activate Auction
            Auction --> SearchController: query result message
            
        SearchController --> AuctionView: query result message
        
      AuctionView --> User: query result message
      
end

opt Filter Search
  User -> AuctionView: 1.2. selectFilterAttributes(filters)
  
  
      AuctionView -> SearchController: 2.2. searchByFilterAttributes(filters)
      
      
        SearchController -> Auction: 3.2. getAuctionList(query)
          
          
            Auction --> SearchController: filter result message
            
            
          deactivate Auction
        SearchController --> AuctionView: filter result message
        
        
      deactivate SearchController
      AuctionView --> User: filter result message
      
      
    deactivate AuctionView
end

@enduml