@startuml UC_4
hide footbox


actor ":User" as User
participant ":PaymentInformationView" as PaymentInformationView
participant ":PaymentController" as PaymentController
participant ":IPaymentInformationDatabase" as PaymentInformation
participant ":BankingSystemBoundary" as BankingSystemBoundary
actor ":BankingSystem" as BankingSystem

User ++
  User -> PaymentInformationView : 1. requestPaymentMethodUpdate()
  activate PaymentInformationView
    PaymentInformationView -> PaymentController : 2. getPaymentMethod ()
    activate PaymentController
      PaymentController -> PaymentInformationView: 3. displayPaymentMethodForm()
      PaymentInformationView --> User: return payment form screen
  User -> PaymentInformationView: 4. fillPaymentInformation()
    PaymentInformationView -> PaymentController: 5.newPaymentInformation()
      PaymentController -> BankingSystemBoundary: 6. authenticateInformation()
      activate BankingSystemBoundary
        BankingSystemBoundary -> BankingSystem: 7. authenticateRequest()
        activate BankingSystem
          BankingSystem --> BankingSystemBoundary: success authentication message
        BankingSystemBoundary --> PaymentController: success authentication message
      PaymentController -> PaymentInformation: 8. setPaymentInformation()
      activate PaymentInformation
        PaymentInformation --> PaymentController: new information message
      deactivate PaymentInformation
      PaymentController --> PaymentInformationView: new information message
    PaymentInformationView --> User: new information message

alt Invalid information
  
  BankingSystem --> BankingSystemBoundary: fail authentication message
  BankingSystem --
    BankingSystemBoundary --> PaymentController: fail authentication message
    
  deactivate BankingSystemBoundary
    PaymentController --> PaymentInformationView: fail authentication message
    
  deactivate PaymentController
    PaymentInformationView --> User: fail authentication message
    
  deactivate PaymentInformationView
end

@enduml