@startuml UC_4
hide footbox

actor ":User" as User
participant ":PaymentInformationView" as PaymentInformationView
participant ":PaymentController" as PaymentController
participant ":IPaymentInformationDatabase" as PaymentInformation
participant ":BankingSystemBoundary" as BankingSystemBoundary
actor ":BankingSystem" as BankingSystem

User ++
  User -> PaymentInformationView : 1. // request payment method update
  activate PaymentInformationView
    PaymentInformationView -> PaymentController : 2. // getPaymentMethod(userId)
    activate PaymentController
      PaymentController --> PaymentInformationView: 3. // displayPaymentMethodForm()
  User -> PaymentInformationView: 4. // fill payment information
    PaymentInformationView -> PaymentController: 5. // newPaymentInformation(info)
      PaymentController --> BankingSystemBoundary: 6. // authenticateInformation(info)
      activate BankingSystemBoundary
        BankingSystemBoundary --> BankingSystem: 7. // authenticateRequest(info)
        activate BankingSystem
          BankingSystem --> BankingSystemBoundary: success authentication message
        BankingSystemBoundary --> PaymentController: success authentication message
      PaymentController -> PaymentInformation: 8. // storeNew \nPaymentInformation(info)
      activate PaymentInformation
        PaymentInformation --> PaymentController: new information message
      deactivate PaymentInformation
      PaymentController --> PaymentInformationView: new information message
    PaymentInformationView --> User: new information message

alt Invalid information
  
  BankingSystem --> BankingSystemBoundary: fail authentication message
  BankingSystem --
    BankingSystemBoundary --> PaymentController: fail authentication message
    
  deactivate BankingSystemBoundary
    PaymentController --> PaymentInformationView: fail authentication message
    
  deactivate PaymentController
    PaymentInformationView --> User: fail authentication message
    
  deactivate PaymentInformationView
end

@enduml