@startuml UC_7
hide footbox

actor ":User" as User
participant ":AuctionDetailView" as AuctionView
participant ":AuctionController" as SearchController
participant ":IAuctionDatabase" as Auction

User ++
  User -> AuctionView: 1. viewAuctionDetails(id)
  activate AuctionView
    AuctionView -> SearchController: 2. getAuctionDetails(id)
    activate SearchController
      SearchController -> Auction: 3. getAuction(id)
        activate Auction
          Auction --> SearchController: query result message
        deactivate Auction
      SearchController --> AuctionView: query result message
    deactivate SearchController
    AuctionView --> User: query result message
  deactivate AuctionView

@enduml