@startuml 
skinparam classAttributeIconSize 0
skinparam linetype ortho
left to right direction
hide circle
class PaymentInformationView {
    - bankName: String
    - accountNumber: String

    + requestPaymentMethodUpdate(userId: Int)
    + dispayPaymentMethodForm()
    + fillPaymentInformation(bankName: String, accountNumber: String)

    }

class PaymentController {
    + getPaymentMethod(userId: Int)
    + newPaymentInformation(bankName: String, accountNumber: String)
    }

class PaymentInformation {
    - id: Int
    - bankName: String
    - accountNumber: String

    + getId(): Int
    + getBankName(): String
    + getAccountNumber(): String
    }

class BankingSystemBoundary {
    + authenticateInformation(bankName: String, accountNumber: String): Boolean
    }

class IPaymentInformationDatabase <<interface>> {
    + createPaymentInformation(bankName: String, accountNumber: String): PaymentInformation
    + getPaymentInformation(id: Int): PaymentInformation
    + setPaymentInformation(id: Int, bankName: String, accountNumber: String)
    }

@enduml