@startuml 
left to right direction
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide circle
class AuctionDetailView <<boundary>> {

    // view auction details ()

    }

class AuctionController <<control>> {
    
    // get auction details ()

    }

class Auction <<entity>> {
    id: Int
    name: String
    start date: String
    end date: String
    create date: String
    status: String
    winner: Int
    bid step: Float
    initial price: Float
    current price: Float
    deposit rate: Float
    // create auction ()
    // get auction list ()
    // set auction ()
    // get auction ()

    }


AuctionDetailView "1" --- "1" AuctionController

AuctionController "1" --- "0..*" Auction


@enduml