@startuml 
left to right direction
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide circle
class AuctionDetailView {

    + viewAuctionDetails(id: Int)

    }

class AuctionController {
    
    + getAuctionDetails(id: Int): Auction

    }

class Auction {
    - id: Int
    - name: String
    - startDate: String
    - endDate: String
    - createDate: String
    - status: String
    - winner: Int
    - winnerPayment: Int
    - participantPaymentList: Map<Int, Int>
    - bidStep: Float
    - initialPrice: Float
    - currentPrice: Float
    - depositRate: Float

    + getId(): Int
    + getName(): String
    + getStartDate(): String
    + getEndDate(): String
    + getCreateDate(): String
    + getStatus(): String
    + getWinner(): Int
    + getBidStep(): Float
    + getInitialPrice(): Float
    + getCurrentPrice(): Float
    + getDepositRate(): Float
    + getRegisterPaymentList(): Map <Int, Int>
    + getWinnerPayment(): Int
    }

class IAuctionDatabase <<interface>> {
    + createAuction(name: String, startDate: String, endDate: String, bidStep: Float, initialPrice: Float): Auction
    + getAuctionList(query: String): List<Auction>
    + setAuction(id: Int, name: String, startDate: String, endDate: String, bidStep: Float, initialPrice: Float)
    + getAuction(id: Int): Auction
    + addRegisterPayment(auctionId: Int, customerId, paymentId: Int)
    + deleteRegisterPayment(auctionId: Int, customerId)
    }

AuctionDetailView "1" -- "1" AuctionController

AuctionController ..r> IAuctionDatabase

IAuctionDatabase ..u> Auction

@enduml