@startuml
hide footbox


actor ":Admin" as Admin
boundary ":VerificationRequestView" as PendingRequestsView
control ":VerificationRequest\nController" as VerificationRequestController
entity ":VerificationRequest" as PendingRequests

Admin ++
  Admin -> PendingRequestsView: 1. // choose view pending requests
  PendingRequestsView ++
    PendingRequestsView -> VerificationRequestController: 2. // get pending requests ()
    VerificationRequestController ++
      VerificationRequestController -> PendingRequests: 3. // query requests ()
        PendingRequests ++
        PendingRequests --> VerificationRequestController: query results message
      VerificationRequestController --> PendingRequestsView: 4. // display pending requests ()


  Admin -> PendingRequestsView: // select specific request
    PendingRequestsView -> VerificationRequestController: // 5. get specific request ()
      VerificationRequestController -> PendingRequests: // 6. query specific request ()
        PendingRequests --> VerificationRequestController: query results message
      VerificationRequestController --> PendingRequestsView: 7. // display specific request ()

  Admin -> PendingRequestsView: // update request status ()
    PendingRequestsView -> VerificationRequestController: // 8. update request ()
      VerificationRequestController -> PendingRequests: // 9. update request ()
        PendingRequests --> VerificationRequestController: update success message
      VerificationRequestController --> PendingRequestsView: updated results message
    PendingRequestsView --> Admin: updated request status message

alt Invalid status
  PendingRequests --> VerificationRequestController: invalid status message
  PendingRequests --
    VerificationRequestController --> PendingRequestsView: error message
    VerificationRequestController --
    PendingRequestsView --> Admin: error message
    PendingRequestsView --
end

@enduml