@startuml cancel_registration
hide footbox

actor ":Customer" as customer
boundary ":AuctionDetailView" as view
control ":AuctionController" as auctionController
control ":PaymentController" as paymentController
entity ":Payment" as payment
boundary ":BankingSystemBoundary" as bankBoundary
actor ":BankingSystem" as bank
entity ":Auction" as auction

autonumber 1 1 "0."

customer ++
customer -> view: // cancel registration ()
activate view
view -> auctionController ++: // cancel registration ()
auctionController -> paymentController ++: // refund ()
paymentController -> payment ++: // get payment detail ()
autonumber stop
payment --> paymentController --: payment details message
autonumber resume
paymentController -> bankBoundary ++: // refund ()
bankBoundary -> bank ++: // refund ()
autonumber stop
bank --> bankBoundary --: refund success message
bankBoundary --> paymentController --: refund success message
paymentController --> auctionController --: refund success message
autonumber resume
auctionController -> auction ++ : // set auction ()
autonumber stop
auction --> auctionController --: cancel registration success message
auctionController --> view --: cancel registration\nsuccess message
view --> customer --: cancel registration\nsuccess message


@enduml