@startuml create_auction
hide footbox
actor ":Seller" as seller
boundary ":CreateAuctionView" as view
control ":AuctionController" as controller
entity ":Auction" as auction

autonumber 1 1 "0."

activate view
activate seller
  seller -> view: // enter information ()
  view -> view: // validate information ()
autonumber stop
  alt valid information
    view -> controller ++: 3.1. // create auction ()
    controller -> auction ++: 4.1. // create auction ()
    auction --> controller --: auction created message
    controller --> view --: auction created message
    view --> seller: auction created message


else missing information
    view --> seller: missing information message
else invalid information
  view --> seller: invalid information message
end
deactivate view


@enduml