@startuml Login
hide footbox
actor "User" as Users
boundary "LoginForm" as LoginBoundary
control "LoginController" as AccountController
entity "Account" as AccountEntity
boundary "DatabaseSystem" as DatabaseBoundary
database "Database" as DatabaseActor

autonumber
autoactivate on
Users -> LoginBoundary: // fill info()

LoginBoundary -> LoginBoundary: // check valid()

alt valid information

    LoginBoundary -> AccountController: // login account()
    AccountController -> AccountEntity: // login account()
    AccountEntity -> DatabaseBoundary: // login account()
    DatabaseBoundary -> DatabaseActor: // login account()

    alt account does exist

        DatabaseActor --> DatabaseBoundary: login success
        DatabaseBoundary --> AccountController: login success
        AccountController --> LoginBoundary: login success
        LoginBoundary --> Users: login success msg

    else account does not existed

        autonumber 7.1 
        DatabaseActor --> DatabaseBoundary: account does not exist
        autonumber inc A
        DatabaseBoundary --> AccountController: account does not exist
        autonumber inc A
        AccountController --> LoginBoundary: account does not exist
        autonumber inc A
        LoginBoundary --> Users: invalid information msg

    end



else invalid information
    
    autonumber 3.1
    LoginBoundary --> Users: invalid input data field msg

end
@enduml