@startuml participate_in_auction
hide footbox

actor ":Customer" as customer
boundary ":AuctionView" as view
control ":AuctionController" as controller
entity ":Auction" as auction

autonumber 1 1 "0."

activate view

customer ++
customer -> view: // request participate ()
view -> controller++: // participate ()
controller -> auction++: // get auction ()
autonumber stop
auction --> controller--: participate successfully
autonumber resume
controller -> view--: // display auction room ()
autonumber stop
view --> customer: return auction room screen

deactivate view

ref over customer, view, controller, auction
  Place bid
end ref

@enduml
