@startuml
hide footbox


actor ":Customer" as Customer
boundary ":AuctionView" as AuctionView
control ":AuctionController" as AuctionController
entity ":Bid" as Bid
Customer ++
  Customer -> AuctionView : 1. // enter bid amount ()
  activate AuctionView
    AuctionView -> AuctionController : 2. // validate bid ()
    activate AuctionController
      AuctionController -> AuctionController : 3. // validate bid ()
      AuctionController -> Bid : 4. // update bid ()
      activate Bid
        Bid --> AuctionController : new highest bid message

      AuctionController --> AuctionView : new highest bid message
    AuctionView --> Customer : new highest bid message

alt Invalid Bid Amount
  AuctionController --> AuctionView : invalid bid message
    AuctionView --> Customer : invalid bid message
end

opt Automatic Bid
    Customer -> AuctionView : 1.1. // set max bid ()
      AuctionView -> AuctionController : 2.1. // set max bid ()
    loop Until Auction Ends
      alt Not Top Bidder & Max Bid Not Exceeded
        AuctionController -> Bid : 3.2 // update bid ()
          Bid --> AuctionController : new highest bid message
        deactivate Bid
          AuctionController --> AuctionView : new highest bid message
        deactivate AuctionController
          AuctionView --> Customer : new highest bid message
        deactivate AuctionView
      end
    end
end

@enduml