@startuml register_to_participate
hide footbox

actor ":Customer" as customer
boundary ":AuctionDetailView" as view
control ":AuctionController" as controller
entity ":Auction" as auction

autonumber 1 1 "0."

customer ++
customer -> view ++: // register to participate ()
autonumber stop
view --> customer: payment information message
ref over customer, view: Make payment
alt payment success
    view -> controller ++ : 2.1. // register to participate ()
    controller -> auction ++ : 3.1. // set auction ()
    auction --> controller --: register success message
    controller --> view: register success message
    view --> customer : register success message
else payment failed
    view --> customer : payment failed message
end

@enduml