@startuml register_car
hide footbox

actor ":Seller" as seller
boundary ":RegisterCarForm" as form
control ":VerificationRequest\nController" as controller
entity ":Car" as car
entity ":VerificationRequest" as request

autonumber 1 1 "0."

activate seller
seller -> form ++: // enter information ()
form -> form : // validate information ()

autonumber stop
alt valid information
  form --> seller : payment information message
  ref over seller, form : Make payment
  alt payment successful
    form -> controller ++: 3.1.1. // submit information ()
    controller -> car ++: 4.1.1 // create car ()
    car --> controller --: car created message
    controller -> request ++: 5.1.1. // create request ()
    request --> controller --: request created message
    controller --> form --: request created message
    form --> seller : request created message
  else payment failed
    form --> seller : payment failed message
  end
else missing information
  form --> seller : missing information message
else invalid information
  form --> seller : invalid information message

end
@enduml