@startuml Update Account Information
hide footbox
actor "User" as Users
boundary "UpdateAccountForm" as UpdateAccountBoundary
control "UpdateAccountController" as AccountController
entity "Account" as AccountEntity
boundary "DatabaseSystem" as DatabaseBoundary
database "Database" as DatabaseActor

autonumber
autoactivate on
Users -> UpdateAccountBoundary: // fill info()

UpdateAccountBoundary -> UpdateAccountBoundary: // check valid()

alt valid information

    UpdateAccountBoundary -> AccountController: // update account info()
    AccountController -> AccountEntity: // update account info()
    AccountEntity -> DatabaseBoundary: // update account info()
    DatabaseBoundary -> DatabaseActor: // update account info()

    DatabaseActor --> DatabaseBoundary: info updated success
    DatabaseBoundary --> AccountController: info updated success
    AccountController --> UpdateAccountBoundary: info updated success
    UpdateAccountBoundary --> Users: info updated successful msg

else invalid information
    
    autonumber 3.1
    UpdateAccountBoundary --> Users: invalid information msg

end
@enduml