@startuml view_registered_auction
hide footbox
actor ":Customer" as customer
boundary ":AuctionListView" as view
control ":AuctionController" as controller
entity ":Auction" as auction

autonumber 1 1 "0."
customer ++
customer -> view ++: // view registered auction ()
view -> controller ++ : // get registered auction ()
controller -> auction ++ : // get auction list ()
autonumber stop
auction --> controller -- : registered auction message
autonumber resume
controller -> view -- : // display registered auction ()
autonumber stop
view --> customer -- : return registered auction screen
' ref over customer, view, controller, auction : View auction information.
@enduml