@startuml view_hosted_auction
hide footbox
actor ":Seller" as seller
boundary ":AuctionListView" as view
control ":AuctionController" as controller
entity ":Auction" as auction

autonumber 1 1 "0."
seller ++
seller -> view ++: // view hosted auction ()
view -> controller ++ : // get hosted auction ()
controller -> auction ++: // get auction list ()
autonumber stop
auction --> controller --: hosted auction message
autonumber resume
controller -> view --: // display hosted auction ()
autonumber stop
view --> seller : return hosted auction screen
' ref over seller, view, controller, auction : View auction information.
@enduml