@startuml
hide footbox

actor ":User" as User
boundary ":AuctionDetailView" as AuctionView
control ":SearchController" as SearchController
entity ":Auction" as Auction

autonumber
  User -> AuctionView: // get auction details()
  activate AuctionView
    AuctionView -> SearchController: // get auction details()
    activate SearchController
      SearchController -> Auction: // query auction details()
        activate Auction
          Auction --> SearchController: query result
        deactivate Auction
      SearchController --> AuctionView: auction information
    deactivate SearchController
    AuctionView --> User: display auction information
  deactivate AuctionView

@enduml