@startuml 
left to right direction
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide circle
class VerificationRequestView <<boundary>> {
    // view pending requests ()
    // view specific request ()
    // update request status ()
    // display error message ()

    }

class VerificationRequestController <<control>> {
    // get pending requests ()
    // get specific request ()
    // update request status ()

    }

class VerificationRequest <<entity>> {
    current owner name: String
    manufacturing brand: String
    model code: String
    manufacturing year: Int
    color: String
    class: String
    number of door: Int
    number of seat: Int
    layout: String
    fuel: String
    transmission: String
    number of cylinder: Int
    engine capacity: Int
    image: String
    location: String

    // get request list ()
    // get request details ()
    // update request status ()
    }


VerificationRequestView "1" --- "1" VerificationRequestController

VerificationRequestController "1" --- "0..*" VerificationRequest


@enduml