@startuml 
skinparam classAttributeIconSize 0
skinparam linetype ortho
left to right direction
hide circle
class PaymentView <<boundary>> {
    pay amount: Float
    payment method: String
    bank name: String
    password: String

    // initiate payment action ()
    // display payment details ()
    // make payment ()
    // provide authentication details ()
    // display payment confirmation ()
    // confirm purchase ()

    }

class PaymentController <<control>> {
    // trigger payment ()
    // make payment ()
    // provide authentication details ()
    // confirm purchase ()

    }

class Payment <<entity>> {
    id: Int
    pay amount: Float
    bank name: String
    account number: String
    user id: Int
    transaction id: String
    // create payment ()
    // set payment detail ()
    // get payment detail ()

    }

class BankingSystemBoundary <<boundary>> {
    // transmit payment request ()
    // transfer encrypted details ()
    // transaction request ()

    }

PaymentView "1..*" --- "1" PaymentController

PaymentController "1" --- "0..*" Payment

PaymentController "1" --- "1" BankingSystemBoundary

@enduml