@startuml 
left to right direction
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide circle
class AuctionView <<boundary>> {
    bid amount: Float

    // fill bid amount ()
    // validate bid amount ()
    // set max bid ()
    // display highest bid ()

    }

class AuctionController <<control>> {
    // validate bid ()
    // update highest bid ()



    }

class Bid <<entity>> {
    amount: Float
    bidder: String
    time stamp: String

    // get bid ()
    // set bid ()
    // update bid ()

    }


AuctionView "1" --- "1" AuctionController

AuctionController "1" --- "0..*" Bid


@enduml