@startuml 
skinparam classAttributeIconSize 0
skinparam linetype ortho
left to right direction
hide circle
class AuctionListView <<boundary>> {

    // search by keywords ()
    // search by filter attributes ()

    }

class SearchController <<control>> {
    
    // query by keywords ()
    // query by attributes ()

    }

class Auction <<entity>> {
    id: Int
    name: String
    start date: String
    end date: String
    create date: String
    status: String
    winner: Int
    bid step: Float
    initial price: Float
    current price: Float
    deposit rate: Float
    // create auction ()
    // get auction list ()
    // set auction ()
    // get auction ()

    }


AuctionListView "1" --- "1" SearchController

SearchController "1" --- "0..*" Auction


@enduml