@startuml 
skinparam classAttributeIconSize 0
skinparam linetype ortho
left to right direction
hide circle
class AuctionListView <<boundary>> {

    // fill search bar ()
    // select filter attributes ()
    // display search results ()

    }

class SearchController <<control>> {
    
    // query auction by keywords ()
    // query auction by attributes ()

    }

class Auction <<entity>> {
    name
    id
    description

    // get auction list ()

    }


AuctionListView "1" --- "1" SearchController

SearchController "1" --- "0..*" Auction


@enduml