@startuml 
skinparam classAttributeIconSize 0
skinparam linetype ortho
left to right direction
hide circle
class PaymentInformationView <<boundary>> {
    bank name: String
    account number: String

    // get payment method ()
    // new payment information ()

    }

class PaymentController <<control>> {
    // display payment method form ()
    // authenticate information ()
    // store new payment information ()

    }

class PaymentInformation <<entity>> {
    id: Int
    bank name: String
    account number: String

    // create payment information ()
    // get payment information ()
    // set payment information ()

    }

class BankingSystemBoundary <<boundary>> {
    

    // authenticate request ()


    }

PaymentInformationView "1..*" --- "1" PaymentController

PaymentController "1" --- "0..*" PaymentInformation

PaymentController "1" --- "1" BankingSystemBoundary

@enduml