@startuml 
left to right direction
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide circle
class AuctionDetailView <<boundary>> {

    // select auction ()

    }

class AuctionController <<control>> {
    
    // query auction by details ()

    }

class Auction <<entity>> {
    name: String
    id: String
    start date: String
    end date: String
    create date: String
    status: String
    winner: String
    bid step: Float
    initial price: Float
    current price: Float
    deposit rate: Float

    // get auction list ()
    // set auction ()
    // get auction ()
    // update auction ()

    }


AuctionDetailView "1" --- "1" AuctionController

AuctionController "1" --- "0..*" Auction


@enduml