@startuml 
left to right direction
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide circle
class AuctionView <<boundary>> {

    // select auction ()

    }

class SearchController <<control>> {
    
    // query auction by details ()

    }

class Auction <<entity>> {
    name
    id
    description
    status
    begin time
    end time
    car information
    initial price
    minimum step
    current price
    deposit cost

    // get auction details ()

    }


AuctionView "1" --- "1" SearchController

SearchController "1" --- "0..*" Auction


@enduml